---
title: "hw1"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1a

```{r}
p1a <- seq(from = 513, to = 182371, by = 9)
tail(p1a)
```
## Problem 1b

```{r}
p1b <- rep("1st", 921390)
head(p1b)
length(p1b)
```

## Problem 1c

```{r}
p1c <- 37:76876
head(p1c)
length(p1c)
```

## Problem 1d

```{r}
p1d <- rep(c("1st", "2nd", "3rd"), each = 928908)
head(p1d)
length(p1d)
```

## Problem 1e

```{r}
p1e <- seq(155, -13875, by = -4)
tail(p1e)
length(p1e)
```

## Problem 1f

```{r}
p1f <- c(seq(50, 100, by = 10), seq(95, 75, by = -5))
p1f                
```

## Problem 1g

```{r}
p1g <- c(rep(20, 4), rep(30, 3), rep(40, 2), 50)
p1g
```

## Problem 1h

```{r}
p1h <- rep(c(2, 1, 0), 5)
p1h
```

## Problem 1i

```{r}
p1i <- c(seq(124, 68, by = -8), seq(63, 38, by = -5))
p1i
```


## Problem 1j

```{r}
p1j <- rep(c("3rd", "2nd", "1st"), 2)
p1j
```

## Problem 2a

```{r}
p2a <- pnorm(29.43, mean = 63, sd = 12)
p2a
```


## Problem 2b

```{r}
p2b <- qnorm(0.05, mean = 63, sd = 12)
p2b
```

## Problem 2c

```{r}
p2c <- 28000 * (1 - pnorm(90, mean = 63, sd = 12))
p2c
```

## Problem 3a

```{r}
p3a <- 1 - dbinom(0, 10, 0.10)
p3a
```

## Problem 3b

```{r}
p3b <- round(1 - pbinom(0:9, 10, 0.10), 3)
p3b
```

## Problem 4

```{r}
myList <- list(
  Name = "Taylor Brown",
  Department = "Statistics",
  Description = "He’s the best",
  Courses = c(Course1 = "STAT 3080", Course2 = "STAT 2559"),
  ActiveTeach = c(Course1 = TRUE, Course2 = FALSE),
  Enr = list(
    Course1 = c(75, 90, 90),
    Course2 = 5
  ),
  Days = list(
    Course1 = matrix(
      c("Monday", "Tuesday", "Tuesday",
        "Wednesday", "Thursday", "Thursday"),
      ncol = 2
    ),
    Course2 = c("Tuesday", "Thursday")
  )
)
myList
```